### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by abgordon** [uhoh-itsmaciek/fretboard.cool#1]
Can you add me as a contributor? I have a tiny PR

**Comment by uhoh-itsmaciek** [comment]
Hi @abgordon, thanks for your interest! The standard workflow for contributions is for you to copy the code to your own repository by clicking the "Fork" button in the upper right, making changes there, and then opening a pull request across repositories. I'll update the README and about page to make that clearer.

I don't want to add others directly right now because changes to master are deployed to fretboard.cool automatically and there's no way to control per-branch permissions.

**Comment by uhoh-itsmaciek** [comment]
Closing this for now--feel free to reopen if you need help, or just open a pull request from your repository.
